# Nombre de la aplicacion para logs y metrics
spring.application.name=pelukeria

# URL de conexion a MySQL: protocolo//host:puerto/bd?desactivarSSL&permitirclavePublica&zonaHoraria
spring.datasource.url=jdbc:mysql://mysql:3306/pbl?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Usuario de la base de datos
spring.datasource.username=root

# Contrasena de la base de datos
spring.datasource.password=pasahitza

# Actualiza automaticamente las tablas segun las entidades JPA (modo desarrollo)
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola para depurar
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect