package edu.mondragon.webengl.pelukeria.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import edu.mondragon.webengl.pelukeria.domain.erabiltzailea.model.Erabiltzailea;
import edu.mondragon.webengl.pelukeria.domain.erabiltzailea.repository.ErabiltzaileaRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
            // Which is auto-generated by Spring, we will use it to handle the data
  private ErabiltzaileaRepository erabiltzaileaRepository;

  @Autowired
  private PasswordEncoder passwordEncoder;

  @GetMapping(path="ping")
  public @ResponseBody String ping() {
      return "pong";
  }
  

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewErabiltzailea (
    @RequestParam String name, 
    @RequestParam String email, 
    @RequestParam String password) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    System.out.println(">>> POST /demo/add llamado <<<");
    System.out.println("name: " + name);
    System.out.println("email: " + email);
    System.out.println("password: " + password);

    Erabiltzailea n = new Erabiltzailea();
    n.setIzena(name);
    n.setGmail(email);
    n.setPasahitza(passwordEncoder.encode(password));
    erabiltzaileaRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Erabiltzailea> getAllErabiltzaileak() {
    // This returns a JSON or XML with the users
    return erabiltzaileaRepository.findAll();
  }
}